-keep class com.flet.serious_python_android.** { *; }
-keep class com.flet.flet_app.ble.** { *; }
-keep class com.flet.flet_app.wifi.** { *; }
-keep class org.jnius.** { *; }
-keepnames class * { *; }