-keep class com.flet.serious_python_android.** { *; }
-keep class org.jnius.** { *; }
-keep class com.magnes.nushuxa.ble.** { *; }
-keep class com.magnes.nushuxa.wifi.** { *; }
-keepnames class * { *; }
